name: Coverage

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install just 📦
        uses: extractions/setup-just@v3
      - name: Install the latest version of uv 📦
        uses: astral-sh/setup-uv@v6
      - name: Install Python 📦
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies 📦
        run: just install
      - name: Run tests and benchmarks ✅
        uses: CodSpeedHQ/action@v3
        with:
          run: just test
      - name: Upload coverage reports to Codecov 🚀
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: auto-token
          plugins: pycoverage,compress-pycoverage
